# Generated by Django 4.0.5 on 2022-06-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.BooleanField()),
                ('yellow', models.BooleanField()),
                ('Beige', models.BooleanField()),
                ('green', models.BooleanField()),
                ('blue', models.BooleanField()),
                ('Navy', models.BooleanField()),
                ('grey', models.BooleanField()),
                ('white', models.BooleanField()),
                ('black', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='pants_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_25', models.BooleanField()),
                ('size_26', models.BooleanField()),
                ('size_27', models.BooleanField()),
                ('size_28', models.BooleanField()),
                ('size_29', models.BooleanField()),
                ('size_30', models.BooleanField()),
                ('size_32', models.BooleanField()),
                ('size_34', models.BooleanField()),
                ('size_36', models.BooleanField()),
                ('size_38', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('imgurl', models.ImageField(blank=True, upload_to='Product/')),
                ('types', models.TextField()),
                ('prise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='shoes_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_210', models.BooleanField()),
                ('size_220', models.BooleanField()),
                ('size_230', models.BooleanField()),
                ('size_240', models.BooleanField()),
                ('size_250', models.BooleanField()),
                ('size_260', models.BooleanField()),
                ('size_270', models.BooleanField()),
                ('size_280', models.BooleanField()),
                ('size_290', models.BooleanField()),
                ('size_300', models.BooleanField()),
                ('size_310', models.BooleanField()),
                ('size_320', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='top_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XS', models.BooleanField()),
                ('S', models.BooleanField()),
                ('M', models.BooleanField()),
                ('L', models.BooleanField()),
                ('XL', models.BooleanField()),
                ('XXL', models.BooleanField()),
                ('XXXL', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('img', models.ImageField(default='profile/default.jpg', upload_to='profile/%Y/%m/%d')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('accessToken', models.TextField()),
                ('max_day', models.DateField()),
                ('refreshToken', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sale', models.IntegerField()),
                ('use', models.BooleanField()),
                ('user_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.user')),
            ],
        ),
        migrations.CreateModel(
            name='Check_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.product')),
                ('user_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.user')),
            ],
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.TextField()),
                ('colors', models.TextField()),
                ('shipping_name', models.TextField()),
                ('shipping_number', models.TextField()),
                ('shipping_address', models.TextField()),
                ('shipping_text', models.TextField()),
                ('prise', models.IntegerField()),
                ('prise_by', models.TextField()),
                ('bate', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.user')),
            ],
        ),
        migrations.CreateModel(
            name='Basket_buy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_name', models.TextField()),
                ('shipping_number', models.TextField()),
                ('shipping_address', models.TextField()),
                ('shipping_text', models.TextField()),
                ('prise', models.IntegerField()),
                ('prise_by', models.TextField()),
                ('bate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wear.user')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.TextField()),
                ('colors', models.TextField()),
                ('Basket_buy_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wear.basket_buy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.user')),
            ],
        ),
    ]
