# Generated by Django 4.0.5 on 2022-06-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wear', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='product',
            new_name='product_by',
        ),
    ]
