# Generated by Django 4.0.5 on 2022-06-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wear', '0002_rename_product_basket_product_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user',
            new_name='user_by',
        ),
    ]
