# Generated by Django 4.0.5 on 2022-06-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wear', '0003_rename_user_basket_user_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyReady',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
                ('colors', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.user')),
            ],
        ),
    ]
